### ISSUE TITLE
Bundle-wide theming

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-core-elements#14]
This feature should make it easy for developers to customize the theme for Vaadin Components.

Polymer cross scope styling (custom properties and mixins) works well and feels natural for CSS developers, but it lacks some of the nice features from the Vaadin Framework Valo theme, like the automatically adjusting colors derived from a base color.

Size variations should be possible to do using standard CSS `calc` function.

We could try to add the missing color manipulation functions, similarly to what Polymer does with `var`. There’s a working draft specification for CSS which we should follow: http://dev.w3.org/csswg/css-color/#modifying-colors

User code:

``` css
v-button {
  --valo-base-color: blue;
}
```

v-button code:

``` css
:host {
  background-color: var(--valo-base-color);
  color: color( var(--valo-base-color) contrast(95%) );
  @apply(--v-button-theme);
}
```

The more advanced features like "bevel", "shadow" and "gradient" could simple be custom properties which are loaded using mixins from separate HTML imports. For example:

valo-3d-theme.html:

``` css
:root {
  --valo-base-color: orange;

  --valo-gradient: linear-gradient( 
      color(var(--valo-base-color) tint(5%)), 
      color(var(--valo-base-color) shade(5%))
  );

  --valo-bevel: 0 1px 0 0 color(var(--valo-base-color) tint(10%)),
               0 -1px 0 0 color(var(--valo-base-color) shade(10%));

  --v-button-theme: {
    background-image: var(--valo-gradient);
    box-shadow: var(--valo-bevel);
  }
}
```

Usage:

``` html
<link rel="import" href="valo-3d-theme.html">
```
